on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno lint
      - run: deno fmt --check
      - run: deno check ./*.ts
      - run: deno test --allow-all --trace-leaks --coverage
      - run: deno coverage
